# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160322_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cost_per_month',
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=450000),
            preserve_default=False,
        ),
    ]
