# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 07:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160322_2332'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
        migrations.AlterField(
            model_name='score',
            name='ujian_praktik',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='ujian_tertulis',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
