# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='no_id',
            field=models.CharField(default=100000000, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
