# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160816_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='no_id',
            new_name='id',
        ),
    ]
