# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20160816_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
