# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.DateTimeField()),
                ('week', models.CharField(choices=[('1', 'week 1'), ('2', 'week 2'), ('3', 'week 3'), ('4', 'week 4')], max_length=1)),
                ('last_active', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
