# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checked_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.TextField(verbose_name=student.models.Student),
        ),
    ]
